---
language: python
python: 3.9

services:
  - docker

install:
  - pip install ansible ansible-lint molecule[docker] testinfra netaddr

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
