---
language: python
python: 3.7

services:
  - docker

install:
  - pip install ansible
  - pip install docker-py==1.9.0
  - pip install molecule
  - mv ../ansible-role-memcached ../hxpro.memcached

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
