---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint molecule/default/
  ansible-lint molecule/default/converge.yml
  flake8 molecule/default/
platforms:
  - name: hxpro-memecached
    image: hxpro/docker-centos
    command: /usr/sbin/init
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
